PREFIX cm: <http://comvantage.eu/graph-trans/class/m#>
PREFIX tm: <http://comvantage.eu/graph-trans/table/m#>
PREFIX c: <http://comvantage.eu/graph-trans/correspondence#>

# create table for each persistent class
# declarative 

INSERT {
    GRAPH <graph://correspondence> {
        [] c:c _:c, _:t;
            c:columnPrefix "".
    }
    GRAPH <graph://table> {
        _:t  a tm:Table;
            tm:name ?name.
#             tm:name ?t_name.
    }
    GRAPH <graph://class> {
        _:c a cm:Class;
            cm:name ?name;
#             cm:name ?c_name;
            cm:is_persistent true.
    }
}
WHERE {
    MINUS { }
#     FILTER (?c_name = ?t_name)
}
