PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX  list:  <http://jena.hpl.hp.com/ARQ/list#>
PREFIX  c:  <http://comvantage.eu/correspondence/>

# Copy insert graphs to minus (step)
# Copy subgraph

# TODO: Check for already used blank nodes

INSERT{
# CONSTRUCT {
    ?item_new a c:Copy.
    ?item c:ref ?item_new.
}
# SELECT DISTINCT  *
WHERE{
    ?item a c:Mark.
    LET (?item_new := if(isBlank(?item), bnode(), ?item))
}

