PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX  list:  <http://jena.hpl.hp.com/ARQ/list#>
PREFIX  c:  <http://comvantage.eu/correspondence/>

# Copy insert graphs to minus (step)
# Copy subgraph

# TODO: Check for already used blank nodes

DELETE{
    ?s ?p ?o.
}
# SELECT DISTINCT  *
WHERE{
    {
        ?s a c:Mark.
        BIND( rdf:type AS ?p )
        BIND( c:Mark AS ?o )
    }
    UNION
    {
        ?s a c:Copy.
        BIND( rdf:type AS ?p )
        BIND( c:Copy AS ?o )
    }
    UNION
    {
        ?s c:ref ?o.
        BIND( c:ref AS ?p )
    }
    
}

