PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX  list:  <http://jena.hpl.hp.com/ARQ/list#>
PREFIX  c:  <http://comvantage.eu/correspondence/>

# Mark start node
# 
INSERT{
    ?item a c:Mark.
}
# SELECT DISTINCT  *
WHERE{
    ?insert_first_item a c:Mark;
        (rdf:rest|rdf:first|sp:elements|sp:graphNameNode|sp:subject|sp:predicate|sp:object|rdf:type)* ?item.
    FILTER (!isLiteral(?item))
}

