PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX  list:  <http://jena.hpl.hp.com/ARQ/list#>

# Converting Modify query to Ask query

DELETE {
    ?el a sp:Modify;
    	sp:insertPattern ?pat.
}
INSERT{
    ?el a sp:Ask.
}
WHERE{
    ?el a sp:Modify;
    	sp:insertPattern ?pat.
}

